export const initialData = {
  boards: [
    {
      _id: "board-1",
      columnOrder: ["column-1", "column-2", "column-3"],
      columns: [
        {
          _id: "column-1",
          boardId: "board-1",
          title: "BrandStorm",
          cardOrder: [
            "card-1",
            "card-5",
            "card-3",
            "card-4",
            "card-2",
            "card-6",
            "card-7",
          ],
          cards: [
            {
              _id: "card-1",
              boardId: "board-1",
              columnId: "column-1",
              title: "The title of card 1",
              cover: null,
            },
            {
              _id: "card-2",
              boardId: "board-1",
              columnId: "column-1",
              title: "The title of card 2",
              cover: null,
            },
            {
              _id: "card-3",
              boardId: "board-1",
              columnId: "column-1",
              title: "The title of card 3",
              cover:
                "https://images.unsplash.com/photo-1492052722242-2554d0e99e3a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80",
            },
            {
              _id: "card-4",
              boardId: "board-1",
              columnId: "column-1",
              title: "The title of card 4",
              cover: null,
            },
            {
              _id: "card-5",
              boardId: "board-1",
              columnId: "column-1",
              title: "The title of card 5",
              cover: null,
            },
            {
              _id: "card-6",
              boardId: "board-1",
              columnId: "column-1",
              title: "The title of card 6",
              cover: null,
            },
            {
              _id: "card-7",
              boardId: "board-1",
              columnId: "column-1",
              title: "The title of card 7",
              cover: null,
            },
          ],
        },
        {
          _id: "column-2",
          boardId: "board-1",
          title: "Rest column",
          cardOrder: ["card-8", "card-9", "card-10"],
          cards: [
            {
              _id: "card-8",
              boardId: "board-1",
              columnId: "column-1",
              title: "The title of card 8",
              cover: null,
            },
            {
              _id: "card-9",
              boardId: "board-1",
              columnId: "column-1",
              title: "The title of card 9",
              cover: null,
            },
            {
              _id: "card-10",
              boardId: "board-1",
              columnId: "column-1",
              title: "The title of card 10",
              cover: null,
            },
          ],
        },
        {
          _id: "column-3",
          boardId: "board-1",
          title: "Rest column",
          cardOrder: ["card-14", "card-11", "card-12", "card-13"],
          cards: [
            {
              _id: "card-11",
              boardId: "board-1",
              columnId: "column-1",
              title: "The title of card 11",
              cover: null,
            },
            {
              _id: "card-12",
              boardId: "board-1",
              columnId: "column-1",
              title: "The title of card 12",
              cover: null,
            },
            {
              _id: "card-13",
              boardId: "board-1",
              columnId: "column-1",
              title: "The title of card 13",
              cover: null,
            },
            {
              _id: "card-14",
              boardId: "board-1",
              columnId: "column-1",
              title: "The title of card 14",
              cover: null,
            },
          ],
        },
      ],
    },
  ],
}
